In [2]:
import numpy as  np

In [3]:
import torch

In [4]:
torch.__version__

'1.6.0'

In [5]:
torch.cuda.is_available()

False

In [67]:
A=np.array([[[[-3,0],[0,5]],[[-15,-5],[5,10]],[[103,200],[-150,-90]]],
            [[[3,0],[0,-3]],[[10,5],[-5,-10]],[[-80,-180],[150,90]]],
           ])
print(A.shape)
print(A)

(2, 3, 2, 2)
[[[[  -3    0]
   [   0    5]]

  [[ -15   -5]
   [   5   10]]

  [[ 103  200]
   [-150  -90]]]


 [[[   3    0]
   [   0   -3]]

  [[  10    5]
   [  -5  -10]]

  [[ -80 -180]
   [ 150   90]]]]


In [69]:
A/150+1


array([[[[ 0.98      ,  1.        ],
         [ 1.        ,  1.03333333]],

        [[ 0.9       ,  0.96666667],
         [ 1.03333333,  1.06666667]],

        [[ 1.68666667,  2.33333333],
         [ 0.        ,  0.4       ]]],


       [[[ 1.02      ,  1.        ],
         [ 1.        ,  0.98      ]],

        [[ 1.06666667,  1.03333333],
         [ 0.96666667,  0.93333333]],

        [[ 0.46666667, -0.2       ],
         [ 2.        ,  1.6       ]]]])

In [87]:
B=A.transpose(0,2,3,1).astype(np.float32)
print(B.shape)
print(B)

(2, 2, 2, 3)
[[[[  -3.  -15.  103.]
   [   0.   -5.  200.]]

  [[   0.    5. -150.]
   [   5.   10.  -90.]]]


 [[[   3.   10.  -80.]
   [   0.    5. -180.]]

  [[   0.   -5.  150.]
   [  -3.  -10.   90.]]]]


In [88]:
var=np.var(B,axis=0)
var

array([[[9.00000e+00, 1.56250e+02, 8.37225e+03],
        [0.00000e+00, 2.50000e+01, 3.61000e+04]],

       [[0.00000e+00, 2.50000e+01, 2.25000e+04],
        [1.60000e+01, 1.00000e+02, 8.10000e+03]]], dtype=float32)

In [89]:
B/=[2,3,4]

In [75]:
B-=mean
B

array([[[[  -3. ,  -12.5,   91.5],
         [   0. ,   -5. ,  190. ]],

        [[   0. ,    5. , -150. ],
         [   4. ,   10. ,  -90. ]]],


       [[[   3. ,   12.5,  -91.5],
         [   0. ,    5. , -190. ]],

        [[   0. ,   -5. ,  150. ],
         [  -4. ,  -10. ,   90. ]]]], dtype=float32)

In [42]:
C=B.transpose(0,3,1,2)
C

array([[[[  -3. ,    0. ],
         [   0. ,    4. ]],

        [[ -12.5,   -5. ],
         [   5. ,   10. ]],

        [[  91.5,  190. ],
         [-150. ,  -90. ]]],


       [[[   3. ,    0. ],
         [   0. ,   -4. ]],

        [[  12.5,    5. ],
         [  -5. ,  -10. ]],

        [[ -91.5, -190. ],
         [ 150. ,   90. ]]]], dtype=float32)

In [70]:
t=np.array([[-10,2,3],[6,2,1]])
t

array([[-10,   2,   3],
       [  6,   2,   1]])

In [71]:
maxim=np.max(np.abs(t),axis=0)
maxim

array([10,  2,  3])

In [65]:
p=t/_

In [66]:
p

array([[-1.        ,  1.        ,  1.        ],
       [ 0.6       ,  1.        ,  0.33333333]])

In [55]:
p.shape

(2, 3)

In [56]:
t.shape

(2, 3)